    type Query {
        files(parentId:String, token:String!): [File]
        file(_id: String! token:String!): File
        getCrumbs(_id: String! token: String!): [String]!
        getStructure(token: String!): [File]
    }

    type FolderChildren {
        childId: ID!,
        childType: String,
        childName: String
    }

    type File {
        _id: ID!,
        name: String,
        type: String,
        uploadDate: String,
        fileSize: Int,
        owner: String!
    }

    input NewFile {
        type: String,
        size: Int!,
        creationDate: Int
    }

    type Mutation {
        renameFile(_id: String!, type: String!, newName: String!, token: String!): Boolean!
        addFolder(parentId: String!, name: String!, token: String!): Boolean!
        remove(_id: [String!], token: String!, type: String!): Boolean!
        generateLink(_id: String!, token: String!): String
    }