type Query {
    authenticate(token:String!) : Boolean!
}

type Session{
    username: String,
    token: String,
    error: String
}

type Mutation {
    createSession(username: String!, pass: String!): Session
}